credentials:
  usernames:
 
    ashita:
      #email: ashita@company.com
      name: Ashita Serrao
      password: '$2b$12$zB3/StzsQg.b8uMZqFp9uOpCblzkWnFBrSIOWDboG35qOnDkz2Ctu'
 
    arvin:
      #email: arvin@company.com
      name: Arvin Shetty
      password: '$2b$12$fJ3MLe83/4PJjv66uZvOweEPXyQpvVVN6pp.wtZRnfJUixE81qGLq'
 
    apu:
      #email: apu@company.com
      name: Apu Halder
      password: '$2b$12$SbhJArr4r5e/.cqlyeej.OK.wfgi7SRdfRiRMuoVtH2PQeZ.IKA6a'
 
    srinivas:
      #email: srinivas@company.com
      name: Chityala Srinivas
      password: '$2b$12$8BfLIn7QdKvLAzQXXidjdudty6pgXmC.s9W13j7SAao9GqCwI.Vwa'
 
    devendra:
      #email: devendra@company.com
      name: Devendra Ramola
      password: '$2b$12$CtkzZ4vOa3mX7f3T7.tEXOcI.jhoJ1YxjXAcLBD5rqQj3ORnce7Re'
 
    pramod:
      #email: pramod@company.com
      name: Pramod Wankhade
      password: '$2b$12$0bOrOvdHRnhdsqYlt8W/NOpzXn2bCQ8VY7FwQJqrJ4jm09qyRlny2'
 
    chandrasekar:
      #email: chandrasekar@company.com
      name: S Chandrasekar
      password: '$2b$12$A2c45Hiyyc3L5AWdHUgGwOYOkBLJpaBzQpRgAlXGtBZwMXu9RvzVm'
 
    sanjay:
      #email: sanjay@company.com
      name: Sanjay Raju
      password: '$2b$12$Bj2qGmbkXn3hK/SXYwUyH.XFdFovyhqHblPiXQr6eD4mO87yTEVBa'
 
    dinesh:
     # email: dinesh@company.com
      name: Dinesh Adkhale
      password: '$2b$12$3BZO/1ZDlH4fnAz6.8ZZi.DqtXtcFbomTpKgxe.SoiPNWLvhE0RBy'
 
    shailendra:
      # email: shailendra@company.com
      name: Shailendra Shukla
      password: '$2b$12$BjtmAkKKcrObqLBiHI.yBeSMSa9h9AUSGVb7OpwwHAFPEU0poLsoC'

    shailendra:
      # email: shailendra@company.com
      name: Shailendra Shukla
      password: '$2b$12$BjtmAkKKcrObqLBiHI.yBeSMSa9h9AUSGVb7OpwwHAFPEU0poLsoC'

    pradeep:
      name: Pradeep Kumar
      password: '$2b$12$llaGAX6EcGYYjkkxTU033u9r9GOWtO9vBDaPeUIOuAUOpIiUCBQb2'
 
    krishna:
      name: Krishna Nand
      password: '$2b$12$0Yuk/4Eri.z6VE1ZuwKLYe2UCj.Wp.TAWnLIG8X/r/UE.aX67DZEG'
  
    shivpratap:
      name: Shiv Pratap Singh Rathore
      password: '$2b$12$/pw5R6y/EaTjVRqDEfTNE.Xw.bIK7GM3eQX1dwdtLviHswCuLhzm.'
  
    manoj:
      name: Manoj Deorao Vairagade
      password: '$2b$12$xzAYllKjtpOCuHls2YAovuPc3bWv0inwE1CwBmIGb1Jta6c2iDxg2'
  
    ram:
      name: Ram Bilash Yadav
      password: '$2b$12$xsaie4J8cZaTeTAsTaM.r.R2iH5clILhwtkqlzgDre3QxaYqYHNF6'
  
    sujeet:
      name: Sujeet Kumar
      password: '$2b$12$MDYbUUWlr7JvfM4c3WrQ9OBgpUxjMHAmKF9xV8lQCivtXiZfITeci'
  
    vinod:
      name: Vinod Mehra
      password: '$2b$12$o6hSaFSLBGv1JMVcXyGkHOTXAXe7mQvQ6gHTm1Z7tguH5eKT8f9KK'
  
cookie:
  expiry_days: 30
  key: freight_platform_secret_key
  name: freight_platform_cookie
 